### PR TITLE
Add comparisons other than equality in Table extraction filter

### PR DESCRIPTION
**Pull request by kdebisschop**
Add ability to handle comparisons other than equality in Table extraction where operator.

### CODE REVIEW

**Comment by ecourtial** [comment]
Nice feature too :)
Same thing here, is it possible to add a new method on the unit test to cover this use case?

**Comment by kdebisschop** [comment]
I'll take a look.

**Comment by kdebisschop** [comment]
Hmmm -- the existing unit test only test that whatever 'where' is gets passed to the Query. I committed that code, but it's really quite pointless in that the previous test already does the same thing.

I haven't figured out a way to peek inside the Query object and get the SQL, which seems the closest to a Unit Test we an do here. I think we'd need an actual database table to actually test the functionality - even including the existing functionality. The existing test returns rows for a where statement of 'query' which by rights should have been rejected as invalid SQL if the test was actually testing operation of the query.

Do you want to create a small integration test using sqlite?

**Comment by ecourtial** [comment]
> Do you want to create a small integration test using sqlite?

If you think you are not able to properly cover this use case, so yes, it would be great :)

**Comment by kdebisschop** [comment]
Apparently I missed your answer to my last comment here -- I'll work on that unit test in the next few days.

**Comment by kdebisschop** [comment]
The updated unit test provides coverage for the extended operators.

**Comment by kdebisschop** [comment]
I'm sure you have real work to do and stuff -- but I'm wondering if I can nudge you to take a look at this. The ability to use comparators other than equals is important for my application and it would be nice if I could base my use of the project on master instead of needing to patch my local first.

**Review by ArthurHoaro — APPROVED** [review]
Usage is similar with what I have seen on SQL query builders, no breaking change, LGTM!

**Comment by kdebisschop** [comment]
Arthur - thanks for the review. I did just notice that "ext-pdo" got added to require-dev, which really is not correct. So I accidentally invalidated your review with a one-line cleanup in 0c739de

**Review by ecourtial — APPROVED** [review]

**Comment by ecourtial** [comment]
@kdebisschop We will tag a new version once we will have merged your other PRs :)

**Pull request merged**
